// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/service/image_service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ImageService {

  /// <summary>Holder for reflection information generated from protos/service/image_service.proto</summary>
  public static partial class ImageServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for protos/service/image_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ImageServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJwcm90b3Mvc2VydmljZS9pbWFnZV9zZXJ2aWNlLnByb3RvEg1pbWFnZV9z",
            "ZXJ2aWNlGh9wcm90b3MvcHJvdG9zL2RlZmluaXRpb25zLnByb3RvMjYKDElt",
            "YWdlU2VydmljZRImCgxtYWtlX3JlcXVlc3QSBi5RdWVyeRoOLlF1ZXJ5UmVz",
            "cG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DefinitionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
